# Generated by Django 4.0 on 2022-02-25 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numeron', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numeron',
            name='number',
        ),
        migrations.AddField(
            model_name='numeron',
            name='number_str',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
            preserve_default=False,
        ),
    ]
