# Generated by Django 4.0 on 2022-02-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numeron', '0003_numeron_line_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeron',
            name='line_id',
            field=models.CharField(max_length=300),
        ),
    ]
